class_name Achievements
extends RefCounted

# ── Таблица достижений ────────────────────────────────────────────────────────
# ФАЙЛ СГЕНЕРИРОВАН: dev/tools/achievements_gd.py из Концепция/Достижения.md.
# Править надо СПЕКУ и перегенерировать — правка здесь потеряется при первой же
# пересборке, а список разъедется со спекой и с выгрузкой в App Store Connect.
#
# Достижение описано счётчиком и порогом, а не «условием». Условие пришлось бы
# вычислять, а счётчик просто лежит, и из него бесплатно получается ПРОЦЕНТ —
# он нужен и полоске на экране, и Game Center, который принимает
# percentComplete, а не «да/нет». Разовые достижения — это goal = 1, отдельного
# вида для них не нужно.
#
# `stat` пока НЕ СЧИТАЕТСЯ НИКЕМ: машинерии счётчиков ещё нет, экран собран на
# моках (см. mock_progress). Имена счётчиков при этом настоящие — под них
# и будут заводиться хуки.
#
# См. /Концепция/Достижения.md

# Вес: 1 бронза (5 очков), 2 серебро (10), 3 золото (20), 4 платина (30).
# Потолок Apple — 100 достижений и 1000 очков суммарно; сходится ровно в 1000.
const TIER_POINTS : Array = [0, 5, 10, 20, 30]
const TIER_NAMES  : Array = ["", "бронза", "серебро", "золото", "платина"]

# Категории в порядке вкладок экрана.
const CATEGORIES : Array = [
	{ "key": "start", "title": "Первые шаги", "tab": "СТАРТ" },
	{ "key": "pizza", "title": "Пицца", "tab": "ПИЦЦА" },
	{ "key": "money", "title": "Деньги", "tab": "ДЕНЬГИ" },
	{ "key": "fat", "title": "Жир", "tab": "ЖИР" },
	{ "key": "campaign", "title": "Кампания и боссы", "tab": "КАМПАНИЯ" },
	{ "key": "endless", "title": "Бесконечный режим", "tab": "БЕСКОНЕЧНЫЙ" },
	{ "key": "skins", "title": "Скины", "tab": "СКИНЫ" },
	{ "key": "skill", "title": "Мастерство", "tab": "МАСТЕРСТВО" },
	{ "key": "codex", "title": "Каталог и предметы", "tab": "КАТАЛОГ" },
	{ "key": "slots", "title": "Автоматы", "tab": "АВТОМАТЫ" },
	{ "key": "leaders", "title": "Таблица лидеров", "tab": "ЛИДЕРЫ" },
	{ "key": "secret", "title": "Скрытые", "tab": "СКРЫТЫЕ" },
]

const ALL : Array = [
	{ "id": "first_flight", "cat": "start", "tier": 1, "wave": 1,
	  "title": "Первый полёт", "desc": "Запусти первый забег",
	  "stat": "runs_total", "goal": 1, "hidden": false, "chain": "", "step": "" },
	{ "id": "first_bite", "cat": "start", "tier": 1, "wave": 1,
	  "title": "Первый укус", "desc": "100 пицц за забег",
	  "stat": "pizzas_run_best", "goal": 100, "hidden": false, "chain": "Пицца за забег", "step": "1 из 3" },
	{ "id": "first_dollar", "cat": "start", "tier": 1, "wave": 1,
	  "title": "Первая копейка", "desc": "50 $ за забег",
	  "stat": "money_run_best", "goal": 50, "hidden": false, "chain": "Деньги за забег", "step": "1 из 2" },
	{ "id": "first_skin", "cat": "start", "tier": 1, "wave": 1,
	  "title": "Новый облик", "desc": "Купи любой скин",
	  "stat": "skins_bought", "goal": 1, "hidden": false, "chain": "", "step": "" },
	{ "id": "first_spin", "cat": "start", "tier": 1, "wave": 1,
	  "title": "Дёрни ручку", "desc": "Сыграй в автомат",
	  "stat": "slot_spins", "goal": 1, "hidden": false, "chain": "Автомат", "step": "1 из 2" },
	{ "id": "first_boss", "cat": "start", "tier": 1, "wave": 1,
	  "title": "Не оглядывайся", "desc": "Дойди до босса",
	  "stat": "boss_reached", "goal": 1, "hidden": false, "chain": "", "step": "" },
	{ "id": "pizza_1k", "cat": "pizza", "tier": 1, "wave": 1,
	  "title": "Проглот", "desc": "1 000 пицц за всё время",
	  "stat": "pizzas_total", "goal": 1000, "hidden": false, "chain": "Пицца за всё время", "step": "1 из 4" },
	{ "id": "pizza_10k", "cat": "pizza", "tier": 2, "wave": 1,
	  "title": "Обжора", "desc": "10 000 пицц",
	  "stat": "pizzas_total", "goal": 10000, "hidden": false, "chain": "Пицца за всё время", "step": "2 из 4" },
	{ "id": "pizza_50k", "cat": "pizza", "tier": 3, "wave": 1,
	  "title": "Пицца-бездна", "desc": "50 000 пицц",
	  "stat": "pizzas_total", "goal": 50000, "hidden": false, "chain": "Пицца за всё время", "step": "3 из 4" },
	{ "id": "pizza_250k", "cat": "pizza", "tier": 4, "wave": 2,
	  "title": "Чёрная дыра", "desc": "250 000 пицц",
	  "stat": "pizzas_total", "goal": 250000, "hidden": false, "chain": "Пицца за всё время", "step": "4 из 4" },
	{ "id": "pizza_run_300", "cat": "pizza", "tier": 2, "wave": 1,
	  "title": "За один присест", "desc": "300 пицц за забег",
	  "stat": "pizzas_run_best", "goal": 300, "hidden": false, "chain": "Пицца за забег", "step": "2 из 3" },
	{ "id": "pizza_run_700", "cat": "pizza", "tier": 3, "wave": 2,
	  "title": "Не подавись", "desc": "700 пицц за забег",
	  "stat": "pizzas_run_best", "goal": 700, "hidden": false, "chain": "Пицца за забег", "step": "3 из 3" },
	{ "id": "money_5k", "cat": "money", "tier": 1, "wave": 1,
	  "title": "Кошелёк", "desc": "5 000 $ заработано",
	  "stat": "money_total", "goal": 5000, "hidden": false, "chain": "Деньги за всё время", "step": "1 из 3" },
	{ "id": "money_50k", "cat": "money", "tier": 2, "wave": 1,
	  "title": "Инвестор", "desc": "50 000 $",
	  "stat": "money_total", "goal": 50000, "hidden": false, "chain": "Деньги за всё время", "step": "2 из 3" },
	{ "id": "money_250k", "cat": "money", "tier": 3, "wave": 2,
	  "title": "Капиталист", "desc": "250 000 $",
	  "stat": "money_total", "goal": 250000, "hidden": false, "chain": "Деньги за всё время", "step": "3 из 3" },
	{ "id": "money_run_200", "cat": "money", "tier": 2, "wave": 1,
	  "title": "Богатый забег", "desc": "200 $ за забег",
	  "stat": "money_run_best", "goal": 200, "hidden": false, "chain": "Деньги за забег", "step": "2 из 2" },
	{ "id": "bag_10", "cat": "money", "tier": 1, "wave": 2,
	  "title": "Мешочник", "desc": "10 мешков денег",
	  "stat": "item:money_bag", "goal": 10, "hidden": false, "chain": "Мешки денег", "step": "1 из 2" },
	{ "id": "bag_100", "cat": "money", "tier": 2, "wave": 2,
	  "title": "Инкассатор", "desc": "100 мешков денег",
	  "stat": "item:money_bag", "goal": 100, "hidden": false, "chain": "Мешки денег", "step": "2 из 2" },
	{ "id": "fat_slim", "cat": "fat", "tier": 1, "wave": 1,
	  "title": "Чуть пополнел", "desc": "Достигни СЛИМ",
	  "stat": "fat_max", "goal": 1, "hidden": false, "chain": "Жир", "step": "1 из 3" },
	{ "id": "fat_fat", "cat": "fat", "tier": 1, "wave": 1,
	  "title": "Жирнеем", "desc": "Достигни ЖИР",
	  "stat": "fat_max", "goal": 2, "hidden": false, "chain": "Жир", "step": "2 из 3" },
	{ "id": "fat_uber", "cat": "fat", "tier": 2, "wave": 1,
	  "title": "Убер-режим", "desc": "Достигни УБЕР",
	  "stat": "fat_max", "goal": 3, "hidden": false, "chain": "Жир", "step": "3 из 3" },
	{ "id": "uber_10", "cat": "fat", "tier": 3, "wave": 1,
	  "title": "Хронически убер", "desc": "УБЕР в 10 забегах",
	  "stat": "uber_runs", "goal": 10, "hidden": false, "chain": "", "step": "" },
	{ "id": "uber_fast", "cat": "fat", "tier": 3, "wave": 2,
	  "title": "Разжирел за минуту", "desc": "УБЕР за первые 60 с забега",
	  "stat": "uber_fast", "goal": 1, "hidden": false, "chain": "", "step": "" },
	{ "id": "diet", "cat": "fat", "tier": 4, "wave": 2,
	  "title": "Диета", "desc": "Пройди эпизод, ни разу не выйдя из СКИННИ",
	  "stat": "skinny_episode", "goal": 1, "hidden": false, "chain": "", "step": "" },
	{ "id": "ep1", "cat": "campaign", "tier": 1, "wave": 1,
	  "title": "Ногой об голову", "desc": "Пройди эпизод 1",
	  "stat": "episodes_done", "goal": 1, "hidden": false, "chain": "Кампания", "step": "1 из 4" },
	{ "id": "ep2", "cat": "campaign", "tier": 2, "wave": 1,
	  "title": "Зубы на улице", "desc": "Пройди эпизод 2",
	  "stat": "episodes_done", "goal": 2, "hidden": false, "chain": "Кампания", "step": "2 из 4" },
	{ "id": "ep3", "cat": "campaign", "tier": 3, "wave": 1,
	  "title": "Кто тут хозяин", "desc": "Пройди эпизод 3",
	  "stat": "episodes_done", "goal": 3, "hidden": false, "chain": "Кампания", "step": "3 из 4" },
	{ "id": "campaign", "cat": "campaign", "tier": 3, "wave": 1,
	  "title": "До конца", "desc": "Пройди всю кампанию",
	  "stat": "campaign_done", "goal": 1, "hidden": false, "chain": "Кампания", "step": "4 из 4" },
	{ "id": "ep_nodmg_1", "cat": "campaign", "tier": 3, "wave": 1,
	  "title": "Без царапины", "desc": "Эпизод 1 без единого урона",
	  "stat": "nodmg_episodes", "goal": 1, "hidden": false, "chain": "Эпизоды без урона", "step": "1 из 2" },
	{ "id": "ep_nodmg_all", "cat": "campaign", "tier": 4, "wave": 2,
	  "title": "Неприкасаемый", "desc": "Все три эпизода без урона",
	  "stat": "nodmg_episodes", "goal": 3, "hidden": false, "chain": "Эпизоды без урона", "step": "2 из 2" },
	{ "id": "croc_nodmg", "cat": "campaign", "tier": 3, "wave": 2,
	  "title": "Зубы мимо", "desc": "Победи Крокера, не получив урона",
	  "stat": "boss_nodmg:croc", "goal": 1, "hidden": false, "chain": "", "step": "" },
	{ "id": "club_nodmg", "cat": "campaign", "tier": 3, "wave": 2,
	  "title": "Фейс об стол", "desc": "Победи Фэт Фейса, не получив урона",
	  "stat": "boss_nodmg:club", "goal": 1, "hidden": false, "chain": "", "step": "" },
	{ "id": "ninja_fast", "cat": "campaign", "tier": 2, "wave": 2,
	  "title": "Быстрая нога", "desc": "Победи Ногу Ниндзя меньше чем за 40 с",
	  "stat": "ninja_fast", "goal": 1, "hidden": false, "chain": "", "step": "" },
	{ "id": "bosses_25", "cat": "campaign", "tier": 2, "wave": 2,
	  "title": "Костолом", "desc": "Победи боссов 25 раз",
	  "stat": "bosses_beaten", "goal": 25, "hidden": false, "chain": "", "step": "" },
	{ "id": "endless_start", "cat": "endless", "tier": 1, "wave": 1,
	  "title": "Пробуй бесконечность", "desc": "Запусти бесконечный",
	  "stat": "endless_runs", "goal": 1, "hidden": false, "chain": "", "step": "" },
	{ "id": "endless_3m", "cat": "endless", "tier": 1, "wave": 1,
	  "title": "Марафонец", "desc": "Выживи 3 минуты",
	  "stat": "endless_best", "goal": 180, "hidden": false, "chain": "Время в бесконечном", "step": "1 из 4" },
	{ "id": "endless_5m", "cat": "endless", "tier": 2, "wave": 1,
	  "title": "Выживший", "desc": "Выживи 5 минут",
	  "stat": "endless_best", "goal": 300, "hidden": false, "chain": "Время в бесконечном", "step": "2 из 4" },
	{ "id": "endless_10m", "cat": "endless", "tier": 3, "wave": 1,
	  "title": "Несгибаемый", "desc": "Выживи 10 минут",
	  "stat": "endless_best", "goal": 600, "hidden": false, "chain": "Время в бесконечном", "step": "3 из 4" },
	{ "id": "endless_15m", "cat": "endless", "tier": 4, "wave": 2,
	  "title": "Вечный", "desc": "Выживи 15 минут",
	  "stat": "endless_best", "goal": 900, "hidden": false, "chain": "Время в бесконечном", "step": "4 из 4" },
	{ "id": "hardcore", "cat": "endless", "tier": 3, "wave": 1,
	  "title": "Всё и сразу", "desc": "Дойди до СУПЕР ХАРДА",
	  "stat": "hardcore_reached", "goal": 1, "hidden": false, "chain": "", "step": "" },
	{ "id": "hardcore_2m", "cat": "endless", "tier": 4, "wave": 2,
	  "title": "За гранью", "desc": "Продержись 2 минуты в СУПЕР ХАРДЕ",
	  "stat": "hardcore_best", "goal": 120, "hidden": false, "chain": "", "step": "" },
	{ "id": "skins_3", "cat": "skins", "tier": 1, "wave": 1,
	  "title": "Гардероб", "desc": "Купи 3 скина",
	  "stat": "skins_owned", "goal": 3, "hidden": false, "chain": "Скины куплены", "step": "1 из 3" },
	{ "id": "skins_7", "cat": "skins", "tier": 2, "wave": 1,
	  "title": "Модник", "desc": "Купи 7 скинов",
	  "stat": "skins_owned", "goal": 7, "hidden": false, "chain": "Скины куплены", "step": "2 из 3" },
	{ "id": "skins_all", "cat": "skins", "tier": 4, "wave": 1,
	  "title": "Полный шкаф", "desc": "Купи все скины",
	  "stat": "skins_owned", "goal": 14, "hidden": false, "chain": "Скины куплены", "step": "3 из 3" },
	{ "id": "lvl5_any", "cat": "skins", "tier": 1, "wave": 1,
	  "title": "Пятёрочка", "desc": "Любой скин до 5-го уровня",
	  "stat": "skin_lvl_max", "goal": 5, "hidden": false, "chain": "Уровни скинов", "step": "1 из 4" },
	{ "id": "lvl10_any", "cat": "skins", "tier": 2, "wave": 1,
	  "title": "Мастер улиц", "desc": "Любой скин до 10-го уровня",
	  "stat": "skin_lvl_max", "goal": 10, "hidden": false, "chain": "Уровни скинов", "step": "2 из 4" },
	{ "id": "lvl10_x3", "cat": "skins", "tier": 3, "wave": 2,
	  "title": "Три мастера", "desc": "Три скина до 10-го уровня",
	  "stat": "skins_at_10", "goal": 3, "hidden": false, "chain": "Уровни скинов", "step": "3 из 4" },
	{ "id": "lvl10_all", "cat": "skins", "tier": 4, "wave": 2,
	  "title": "Легенда улиц", "desc": "Все скины до 10-го уровня",
	  "stat": "skins_at_10", "goal": 14, "hidden": false, "chain": "Уровни скинов", "step": "4 из 4" },
	{ "id": "fitting_room", "cat": "skins", "tier": 2, "wave": 2,
	  "title": "Примерочная", "desc": "Сыграй забег каждым купленным скином",
	  "stat": "all_skins_played", "goal": 1, "hidden": false, "chain": "", "step": "" },
	{ "id": "spell_100", "cat": "skins", "tier": 2, "wave": 2,
	  "title": "Заклинатель", "desc": "Примени спелл скина 100 раз",
	  "stat": "spell_casts", "goal": 100, "hidden": false, "chain": "Спеллы скина", "step": "1 из 2" },
	{ "id": "spell_1000", "cat": "skins", "tier": 3, "wave": 2,
	  "title": "Колдун", "desc": "Примени спелл скина 1 000 раз",
	  "stat": "spell_casts", "goal": 1000, "hidden": false, "chain": "Спеллы скина", "step": "2 из 2" },
	{ "id": "viking_50", "cat": "skins", "tier": 2, "wave": 2,
	  "title": "Кулак севера", "desc": "Разбей 50 предметов кулаком викинга",
	  "stat": "spell_hits:viking", "goal": 50, "hidden": false, "chain": "", "step": "" },
	{ "id": "spider_50", "cat": "skins", "tier": 2, "wave": 2,
	  "title": "Паутина в дело", "desc": "Притяни 50 предметов Спайди",
	  "stat": "spell_hits:spider_man", "goal": 50, "hidden": false, "chain": "", "step": "" },
	{ "id": "resist_10", "cat": "skill", "tier": 1, "wave": 2,
	  "title": "Броня", "desc": "10 сработавших резистов",
	  "stat": "resists", "goal": 10, "hidden": false, "chain": "Резисты", "step": "1 из 2" },
	{ "id": "resist_200", "cat": "skill", "tier": 3, "wave": 2,
	  "title": "Непробиваемый", "desc": "200 сработавших резистов",
	  "stat": "resists", "goal": 200, "hidden": false, "chain": "Резисты", "step": "2 из 2" },
	{ "id": "safe_resist", "cat": "skill", "tier": 2, "wave": 2,
	  "title": "Сейф не помеха", "desc": "Переживи сейф на резисте",
	  "stat": "safe_resist", "goal": 1, "hidden": false, "chain": "", "step": "" },
	{ "id": "clean_60", "cat": "skill", "tier": 2, "wave": 1,
	  "title": "Минута чисто", "desc": "60 с подряд без урона",
	  "stat": "clean_best", "goal": 60, "hidden": false, "chain": "Без удара подряд", "step": "1 из 2" },
	{ "id": "clean_180", "cat": "skill", "tier": 3, "wave": 1,
	  "title": "Три минуты чисто", "desc": "180 с подряд без урона",
	  "stat": "clean_best", "goal": 180, "hidden": false, "chain": "Без удара подряд", "step": "2 из 2" },
	{ "id": "curse_survive", "cat": "skill", "tier": 2, "wave": 2,
	  "title": "Мимо шамана", "desc": "Переживи проклятие шамана, не потеряв жизнь",
	  "stat": "curse_survived", "goal": 1, "hidden": false, "chain": "", "step": "" },
	{ "id": "reflex_5", "cat": "skill", "tier": 2, "wave": 2,
	  "title": "Паучья реакция", "desc": "5 уводов реакцией за один забег",
	  "stat": "reflex_run_best", "goal": 5, "hidden": false, "chain": "", "step": "" },
	{ "id": "timestop_10", "cat": "skill", "tier": 2, "wave": 2,
	  "title": "Хозяин времени", "desc": "10 остановок времени",
	  "stat": "time_stops", "goal": 10, "hidden": false, "chain": "", "step": "" },
	{ "id": "codex_25", "cat": "codex", "tier": 1, "wave": 1,
	  "title": "Полкниги", "desc": "Открой 25 записей каталога",
	  "stat": "codex_seen", "goal": 25, "hidden": false, "chain": "Каталог", "step": "1 из 2" },
	{ "id": "codex_all", "cat": "codex", "tier": 3, "wave": 1,
	  "title": "Всё видел", "desc": "Открой весь каталог",
	  "stat": "codex_seen", "goal": 54, "hidden": false, "chain": "Каталог", "step": "2 из 2" },
	{ "id": "magicbox_50", "cat": "codex", "tier": 2, "wave": 2,
	  "title": "Открывашка", "desc": "Поймай 50 мэджик боксов",
	  "stat": "item:magic_box", "goal": 50, "hidden": false, "chain": "", "step": "" },
	{ "id": "mutagen_10", "cat": "codex", "tier": 1, "wave": 2,
	  "title": "Мутант", "desc": "Сыграй 10 жиробоссов",
	  "stat": "minigame:fat_boss", "goal": 10, "hidden": false, "chain": "", "step": "" },
	{ "id": "pack_10", "cat": "codex", "tier": 1, "wave": 2,
	  "title": "Пицца-пати", "desc": "Сыграй 10 пицца-пати",
	  "stat": "minigame:pizza_party", "goal": 10, "hidden": false, "chain": "", "step": "" },
	{ "id": "girl_20", "cat": "codex", "tier": 2, "wave": 2,
	  "title": "Зазывала", "desc": "Поймай 20 девочек-зазывал",
	  "stat": "item:girl", "goal": 20, "hidden": false, "chain": "", "step": "" },
	{ "id": "slot_x3", "cat": "slots", "tier": 1, "wave": 1,
	  "title": "Три в ряд", "desc": "Совпадение ×3",
	  "stat": "slot_best_match", "goal": 3, "hidden": false, "chain": "", "step": "" },
	{ "id": "slot_100", "cat": "slots", "tier": 2, "wave": 1,
	  "title": "Азартный", "desc": "100 спинов",
	  "stat": "slot_spins", "goal": 100, "hidden": false, "chain": "Автомат", "step": "2 из 2" },
	{ "id": "slot_jackpot", "cat": "slots", "tier": 2, "wave": 2,
	  "title": "Джекпот", "desc": "Возьми максимальный выигрыш",
	  "stat": "slot_jackpot", "goal": 1, "hidden": false, "chain": "", "step": "" },
	{ "id": "top100", "cat": "leaders", "tier": 2, "wave": 1,
	  "title": "Сотня", "desc": "Попади в топ-100 недели",
	  "stat": "best_rank_inv", "goal": 1, "hidden": false, "chain": "Место в таблице", "step": "1 из 3" },
	{ "id": "top10", "cat": "leaders", "tier": 3, "wave": 1,
	  "title": "Десятка", "desc": "Попади в топ-10 недели",
	  "stat": "best_rank_inv", "goal": 91, "hidden": false, "chain": "Место в таблице", "step": "2 из 3" },
	{ "id": "top1", "cat": "leaders", "tier": 4, "wave": 2,
	  "title": "Первый", "desc": "Возьми 1-е место недели",
	  "stat": "best_rank_inv", "goal": 100, "hidden": false, "chain": "Место в таблице", "step": "3 из 3" },
	{ "id": "all_modes", "cat": "leaders", "tier": 2, "wave": 2,
	  "title": "Во всех четырёх", "desc": "Попади в таблицу всех четырёх режимов за одну неделю",
	  "stat": "modes_ranked_week", "goal": 4, "hidden": false, "chain": "", "step": "" },
	{ "id": "barrel_death", "cat": "secret", "tier": 1, "wave": 2,
	  "title": "Бочка судьбы", "desc": "Умри от бочки бомжа",
	  "stat": "death_by:bum_barrel", "goal": 1, "hidden": true, "chain": "", "step": "" },
	{ "id": "night_owl", "cat": "secret", "tier": 1, "wave": 2,
	  "title": "Ночная смена", "desc": "Сыграй забег между 3:00 и 5:00",
	  "stat": "night_run", "goal": 1, "hidden": true, "chain": "", "step": "" },
	{ "id": "remote_10", "cat": "secret", "tier": 1, "wave": 2,
	  "title": "Пульт нашёлся", "desc": "Кинь пульт в телевизор 10 раз",
	  "stat": "tv_remote", "goal": 10, "hidden": true, "chain": "", "step": "" },
	{ "id": "pacifist", "cat": "secret", "tier": 2, "wave": 2,
	  "title": "Пацифист", "desc": "Пройди эпизод, ни разу не применив спелл скина",
	  "stat": "no_spell_episode", "goal": 1, "hidden": true, "chain": "", "step": "" },
]

static func by_id(aid: String) -> Dictionary:
	for a in ALL:
		if String(a["id"]) == aid:
			return a
	return {}

static func in_category(key: String) -> Array:
	var out : Array = []
	for a in ALL:
		if String(a["cat"]) == key:
			out.append(a)
	return out

static func points(a: Dictionary) -> int:
	return int(TIER_POINTS[int(a["tier"])])

static func total_points() -> int:
	var n := 0
	for a in ALL:
		n += points(a)
	return n

