extends RefCounted

# ── АНГЛИЙСКАЯ ТАБЛИЦА ───────────────────────────────────────────────────────
# Ключ — РУССКАЯ НАДПИСЬ ИЗ КОДА, слово в слово. Почему так, а не отдельными
# именами вроде «MENU_PLAY» — см. scripts/loc.gd.
#
# Отсюда следует главное правило: поправил надпись в коде — поправь и здесь.
# Иначе перевод молча отвалится к русскому, и заметить это можно будет только
# глазами и только на английском телефоне. За этим следит dev/smoke_i18n.gd: он
# сверяет каждый ключ с исходниками и падает на тех, которых в коде больше нет.
#
# ── ЧЕГО ЗДЕСЬ НЕТ ──────────────────────────────────────────────────────────
# 1. ДЕВ-КНОПОК. «СБРОС УР.», «БЕСС: ON», строки проверки пушей — их не видит
#    ни один игрок (DevFlags.ENABLED), и перевод им только мешает искать.
# 2. ИМЁН СОБСТВЕННЫХ. «НОРМАЛЬДО», «КУСС», «ГЛАЙД» — это имена, а не слова.
# 3. СТРОК С ПОДСТАНОВКОЙ («УРОВЕНЬ %d · %s»). Их перевод требует правки места
#    вызова: переводить надо заготовку, ДО `%`, иначе ключа с готовым числом в
#    таблице не найдётся. Они пойдут отдельным заходом.
#
# ── О ТОНЕ ──────────────────────────────────────────────────────────────────
# Игра разговаривает коротко и на «ты». Английский держит тот же тон: рубленые
# строчные команды, без вежливых оборотов. «EAT PIZZA», а не «Please eat pizza».
# Строки стоят в кнопках и облачках шириной в пол-экрана, поэтому длина
# сопоставима с русской — перевод, вылезающий за кнопку, хуже непереведённого.

const STRINGS : Dictionary = {
	# ── Главное меню ─────────────────────────────────────────────────────────
	"Нажмите, чтобы начать игру": "Tap to play",
	"СКИНЫ":            "SKINS",
	"СЛОТЫ":            "SLOTS",
	"ЗАДАНИЯ":          "QUESTS",
	"ЛИДЕРЫ":           "LEADERS",
	"ДОСТИЖЕНИЯ":       "AWARDS",
	"КНИГА УЧИТЕЛЯ":    "TEACHER'S BOOK",
	"КНИГА\nУЧИТЕЛЯ":   "TEACHER'S\nBOOK",
	"НАСТРОЙКИ":        "SETTINGS",
	"МАГАЗИН":          "SHOP",
	"Магазин":          "Shop",
	"МОИ СКИНЫ":        "MY SKINS",
	"Мои скины":        "My skins",
	"МОЙ БАЛАНС":       "MY BALANCE",
	"Мой баланс":       "My balance",
	"ЭПИЗОД 1":         "EPISODE 1",

	# ── Подсказки по меню ────────────────────────────────────────────────────
	"ДАВАЙ СРАЗУ К ДЕЛУ!":            "STRAIGHT TO IT!",
	"тапни сюда — и побежали":        "tap here and run",
	"тапни по центру — и побежали":   "tap the middle and run",
	"сюда уходят собранные доллары":  "your dollars go here",
	"тут награда за то, что уже сыграл": "your reward for runs already played",
	"тут считают всё, что ты успел":  "everything you've done is counted here",
	"упал жетон — здесь его крутят":  "got a token? spend it here",
	"открылась история — она тут":    "the story unlocked — it's in here",
	"твой результат уже в таблице недели": "your score is already in this week's table",

	# ── Подсказки-облачка ────────────────────────────────────────────────────
	"ПОНЯТНО":          "GOT IT",
	"ДАЛЬШЕ ›":         "NEXT ›",
	"▼ ТАП ▼":          "▼ TAP ▼",

	# ── Забег ────────────────────────────────────────────────────────────────
	"ПАУЗА":            "PAUSE",
	"ПРОДОЛЖИТЬ":       "RESUME",
	"ВЫЙТИ":            "QUIT",
	"ВЫХОД":            "EXIT",
	"ОСТАТЬСЯ":         "STAY",
	"ВЫЙТИ ИЗ ЗАБЕГА?": "QUIT THE RUN?",
	"Пиццы и доллары этого забега не засчитаются":
		"Pizza and dollars from this run won't count",
	"ЭТОТ ЗАБЕГ":       "THIS RUN",
	"ВРЕМЯ":            "TIME",
	"ЗАДАНИЯ ДНЯ":      "DAILY QUESTS",
	"Заданий пока нет": "No quests yet",
	"Рекорда пока нет": "No record yet",
	"Слот на кулдауне": "Slot on cooldown",
	"ГОТОВО — ЗАБЕРИ НАГРАДУ": "DONE — CLAIM YOUR REWARD",
	"ЗАБРАНО":          "CLAIMED",
	"ЗАБРАТЬ":          "CLAIM",
	"ЗАБРАТЬ!":         "CLAIM!",
	"ЗАДАНИЕ":          "QUEST",
	"ЗАДАНИЕ ВЫПОЛНЕНО": "QUEST COMPLETE",
	"ВЫПОЛНЕНО: ":      "DONE: ",
	"новое завтра":     "new one tomorrow",

	# ── Конец забега ─────────────────────────────────────────────────────────
	"ЗАБЕГ ОКОНЧЕН":    "RUN OVER",
	"ЕЩЁ РАЗ":          "AGAIN",
	"ЗАНОВО":           "RESTART",
	"МЕНЮ":             "MENU",
	"ПОБЕДА!":          "VICTORY!",
	"ВЫЙГРАЛ":          "YOU WIN",
	"ДОСТИЖЕНИЕ ОТКРЫТО": "AWARD UNLOCKED",
	"БЕСКОНЕЧНЫЙ РЕЖИМ ОТКРЫТ!": "ENDLESS MODE UNLOCKED!",
	"РАЗБЛОКИРОВАНО:\nБЕСКОНЕЧНЫЙ РЕЖИМ": "UNLOCKED:\nENDLESS MODE",
	"Ещё ни одного забега": "No runs yet",
	"ПЕРВЫЙ ЗАБЕГ ЭТИМ СКИНОМ": "FIRST RUN WITH THIS SKIN",
	"МАСТЕРСТВО":       "MASTERY",
	"МАСТЕРСТВО!":      "MASTERY!",
	"★ МАСТЕРСТВО":     "★ MASTERY",
	"МАСТЕРСТВО:":      "MASTERY:",
	"ОПЫТ":             "XP",
	"+1 ЖЕТОН / 200 XP": "+1 TOKEN / 200 XP",

	# ── Обучение ─────────────────────────────────────────────────────────────
	"ВЕДИ ПАЛЬЦЕМ":     "DRAG YOUR FINGER",
	"голова идёт следом": "the head follows it",
	"ЕШЬ ПИЦЦУ":        "EAT PIZZA",
	"это очки и вес":   "that's points and weight",
	"МУСОР — ОБЛЕТАЙ":  "DODGE THE JUNK",
	"в него нельзя":    "don't touch it",
	"ПОТЕРЯЛ ВЕС":      "LOST WEIGHT",
	"в следующий раз облетай": "go around it next time",
	"ВОТ ТАК":          "JUST LIKE THAT",
	"ТЫ ДОЛЖЕН БЫЛ УМЕРЕТЬ": "THAT SHOULD HAVE KILLED YOU",
	"в обучении прощаем — но только раз": "we forgive it once, and only once",
	"ЭТО БЫЛА ЖИЗНЬ":   "THAT WAS A LIFE",
	"их у тебя столько, сколько веса": "you have as many as you have weight",
	"КОГДА ОСТАНЕТСЯ ЧЕРЕП": "ONCE ONLY THE SKULL IS LEFT",
	"следующий удар будет последним": "the next hit is your last",
	"ВЕС — ЭТО ЖИЗНИ":  "WEIGHT IS LIVES",
	"полоса слева: удар съедает одну": "the bar on the left: a hit eats one",
	"БЬЁТ НЕ ВСЁ":      "NOT EVERYTHING HURTS",
	"банан не ударит, но замедлит": "a banana won't hit you, but it slows you",
	"А ЭТО — БОНУС":    "AND THIS IS A BONUS",
	"часы замедлят мир, хватай": "the clock slows the world — grab it",
	"СОБИРАЙ ДОЛЛАРЫ":  "COLLECT DOLLARS",
	"на них можно купить крутые скины": "they buy you cool skins",
	"ДВОЙНОЙ ТАП":      "DOUBLE TAP",
	"это способность скина": "that's your skin's ability",
	"ТЕПЕРЬ ТЫ ГОТОВ":  "YOU'RE READY NOW",
	"предметов много, обо всех не расскажешь — удачи!":
		"there are far more items than we can show — good luck!",
	"ПРОПУСТИТЬ":       "SKIP",

	# ── Скины ────────────────────────────────────────────────────────────────
	"СПОСОБНОСТИ":      "ABILITIES",
	"ПРОКАЧКА":         "PROGRESS",
	"НАГРАДЫ ЗА УРОВЕНЬ": "LEVEL REWARDS",
	"НАГРАДЫ ЗА УРОВНИ": "LEVEL REWARDS",
	"Награды за уровень": "Level rewards",
	"СОСТОЯНИЯ ЖИРА":   "FAT STATES",
	"ЖИРОВЫЕ СОСТОЯНИЯ": "FAT STATES",
	"АКТИВНАЯ":         "ACTIVE",
	"ПАССИВНАЯ":        "PASSIVE",
	"РЕЗИСТ":           "RESIST",
	"УНИКАЛЬНО":        "UNIQUE",
	"АКТИВЕН":          "EQUIPPED",
	"НАДЕТЬ":           "EQUIP",
	"КУПИТЬ":           "BUY",
	"ЗАКРЫТО":          "LOCKED",
	"ЗАКРЫТЬ":          "CLOSE",
	"ПОДРОБНЕЕ":        "DETAILS",
	"ВЗЯТО":            "TAKEN",
	"НОВЫЙ ЖИР":        "NEW FAT",
	"НОВЫЙ ЖИР!":       "NEW FAT!",
	"НОВЫЙ РЕЗИСТ!":    "NEW RESIST!",
	"+ РЕЗИСТ":         "+ RESIST",
	"НЕТ НАВЫКОВ":      "NO SKILLS",
	"НАВЫКИ":           "SKILLS",
	"Нет навыков — чистая проверка скилла": "No skills — pure skill check",
	"Новое состояние и +1 жизнь": "A new state and +1 life",
	"Негативный эффект снижен на 50%": "Negative effect cut by 50%",
	"Уникальная способность": "Unique ability",
	"Каждый жир — это ещё один пропущенный удар: чем толще Нормальдо, тем больше запаса прочности перед гибелью.":
		"Every fat state is one more hit you can take: the fatter Normaldo is, the more room you have before you die.",
	"АДАПТАЦИЯ":        "ADAPTATION",
	"Адаптация":        "Adaptation",
	"ТРАНСФОРМАЦИЯ":    "TRANSFORMATION",
	"Трансформация":    "Transformation",
	"УКЛОНЕНИЕ":        "EVASION",
	"Уклонение":        "Evasion",
	"КОНТР-УДАР":       "COUNTER",
	"Контратака":       "Counter",
	"МАГНИТ":           "MAGNET",
	"УСКОРЕНИЕ":        "SPEED UP",
	"КОЛДОВСТВО":       "SORCERY",
	"ВСЁ И СРАЗУ":      "ALL AT ONCE",
	"БОНУС":            "BONUS",
	"+бонус":           "+bonus",

	# ── Настройки ────────────────────────────────────────────────────────────
	"ЗВУК И ОТДАЧА":    "SOUND & HAPTICS",
	"Громкость звуков": "Sound volume",
	"Громкость музыки": "Music volume",
	"Вибрация":         "Vibration",
	"Отдача на ударах боссов и в мини-играх.": "Haptics on boss hits and in mini-games.",
	"ЯЗЫК":             "LANGUAGE",
	"УВЕДОМЛЕНИЯ":      "NOTIFICATIONS",
	"Все уведомления":  "All notifications",
	"КАТЕГОРИИ":        "CATEGORIES",
	"Ежедневные напоминания": "Daily reminders",
	"Возвращение в игру": "Come back to the game",
	"Бесплатный спин в автомате": "Free spin in the machine",
	"События и новый контент": "Events and new content",
	"Сюжет и босс":     "Story and boss",
	"Серверные награды": "Server rewards",
	"ТИХИЕ ЧАСЫ":       "QUIET HOURS",
	"Начало":           "From",
	"Конец":            "To",
	"Если в системных настройках уведомления для Normaldo выключены — переключатели ничего не делают.":
		"If notifications for Normaldo are off in your system settings, these switches do nothing.",
	"ПРОФИЛЬ":          "PROFILE",
	"АККАУНТ":          "ACCOUNT",
	"ИМЯ В ТАБЛИЦЕ ЛИДЕРОВ": "LEADERBOARD NAME",
	"ИЗМЕНИТЬ ИМЯ":     "CHANGE NAME",
	"КОД ВОССТАНОВЛЕНИЯ": "RECOVERY CODE",
	"КОПИРОВАТЬ":       "COPY",
	"код скопирован":   "code copied",
	"ВОССТАНОВИТЬ АККАУНТ": "RESTORE ACCOUNT",
	"ВОССТАНОВИТЬ":     "RESTORE",
	"ПРОЖИТОЕ":         "LIFETIME",
	"Забегов":          "Runs",
	"Съедено пиццы":    "Pizza eaten",
	"Лучший забег":     "Best run",
	"Эпизодов пройдено": "Episodes cleared",
	"Скинов открыто":   "Skins unlocked",
	"Прогресс скина":   "Skin progress",
	"Наград книги":     "Book rewards",
	"Таблица лидеров":  "Leaderboard",
	"РЕКОРДЫ НЕДЕЛИ":   "THIS WEEK'S RECORDS",
	"ПРОШЛАЯ НЕДЕЛЯ":   "LAST WEEK",
	"Пока пусто":       "Nothing yet",
	"сыграй забег":     "play a run",
	"ВКЛ":              "ON",
	"ВЫКЛ":             "OFF",
	"Включить":         "Turn on",
	"ВКЛЮЧИТЬ":         "TURN ON",
	"Не сейчас":        "Not now",
	"НЕ СЕЙЧАС":        "NOT NOW",
	"ОТМЕНА":           "CANCEL",
	"СОХРАНИТЬ":        "SAVE",
	"ГОТОВО":           "DONE",
	"Сохраняю…":        "Saving…",
	"Восстанавливаю…":  "Restoring…",
	"Готово, перезагружаю…": "Done, restarting…",
	"Введи имя…":       "Enter a name…",
	"3–12 символов, буквы/цифры. Имя должно быть уникальным.":
		"3–12 characters, letters/digits. The name must be unique.",
	"Имя должно быть от 3 до 12 символов": "The name must be 3 to 12 characters",
	"Имя не подходит — буквы/цифры/-/_": "Bad name — letters/digits/-/_ only",
	"Разрешены только буквы, цифры, _ и -": "Only letters, digits, _ and - are allowed",
	"Это имя занято — попробуй другое": "That name is taken — try another",
	"Не получилось сохранить, попробуй ещё раз": "Couldn't save, try again",
	"Не удалось восстановить": "Couldn't restore",
	"Код в неверном формате": "Wrong code format",
	"Код не найден":    "Code not found",
	"Код слишком короткий": "Code is too short",
	"Запасной ключ к аккаунту. Поменяешь телефон или удалишь игру — введи его, и весь прогресс вернётся. Сохрани в надёжном месте и никому не показывай.":
		"A spare key to your account. Change phones or delete the game, enter it, and all your progress comes back. Keep it somewhere safe and show it to no one.",
	"Включить, чтобы не пропускать ежедневный бонус, новые задания и награды за уровни скина?":
		"Turn on so you don't miss the daily bonus, new quests and skin level rewards?",

	# ── Режимы и уровни ──────────────────────────────────────────────────────
	"БЕСКОНЕЧНЫЙ":      "ENDLESS",
	"СУПЕР ХАРД":       "SUPER HARD",
	"ЛЁГКОЕ":           "EASY",
	"СРЕДНЕЕ":          "MEDIUM",
	"ТЯЖЁЛОЕ":          "HARD",
	"МАКСИМУМ":         "MAX",
	"ОТСЮДА ЗАБЕГ":     "RUN STARTS HERE",
	"ЖИР":              "FAT",
	"Откат ":           "Cooldown ",

	# ── Достижения: разделы и медали ─────────────────────────────────────────
	"ПИЦЦА":            "PIZZA",
	"Пицца":            "Pizza",
	"ДЕНЬГИ":           "MONEY",
	"Деньги":           "Money",
	"КАМПАНИЯ":         "CAMPAIGN",
	"Кампания":         "Campaign",
	"Кампания и боссы": "Campaign and bosses",
	"АВТОМАТЫ":         "MACHINES",
	"Автоматы":         "Machines",
	"Автомат":          "Machine",
	"КАТАЛОГ":          "CATALOGUE",
	"Каталог":          "Catalogue",
	"Каталог и предметы": "Catalogue and items",
	"СКРЫТЫЕ":          "HIDDEN",
	"Скрытые":          "Hidden",
	"СТАРТ":            "START",
	"Скины":            "Skins",
	"Жир":              "Fat",
	"Резисты":          "Resists",
	"Мастерство":       "Mastery",
	"бронза":           "bronze",
	"серебро":          "silver",
	"золото":           "gold",
	"платина":          "platinum",
	"1 из 2":           "1 of 2",
	"2 из 2":           "2 of 2",
	"1 из 3":           "1 of 3",
	"2 из 3":           "2 of 3",
	"3 из 3":           "3 of 3",
	"1 из 4":           "1 of 4",
	"2 из 4":           "2 of 4",
	"3 из 4":           "3 of 4",
	"4 из 4":           "4 of 4",

	# ── Достижения: названия ─────────────────────────────────────────────────
	"Первые шаги":      "First Steps",
	"Первый укус":      "First Bite",
	"Первая копейка":   "First Penny",
	"Первый полёт":     "First Flight",
	"Первый":           "First",
	"Сотня":            "Century",
	"Проглот":          "Gulper",
	"Обжора":           "Glutton",
	"Пицца-бездна":     "Pizza Abyss",
	"Чёрная дыра":      "Black Hole",
	"За один присест":  "In One Sitting",
	"Не подавись":      "Don't Choke",
	"Кошелёк":          "Wallet",
	"Инвестор":         "Investor",
	"Капиталист":       "Capitalist",
	"Богатый забег":    "Rich Run",
	"Инкассатор":       "Cash Courier",
	"Мешочник":         "Bagman",
	"Мешки денег":      "Money Bags",
	"Диета":            "Diet",
	"Чуть пополнел":    "Filled Out a Bit",
	"Жирнеем":          "Getting Fat",
	"За гранью":        "Beyond",
	"Убер-режим":       "Uber Mode",
	"Хронически убер":  "Chronically Uber",
	"Разжирел за минуту": "Fat in a Minute",
	"Броня":            "Armour",
	"Непробиваемый":    "Impenetrable",
	"Неприкасаемый":    "Untouchable",
	"Несгибаемый":      "Unbreakable",
	"Без царапины":     "Without a Scratch",
	"Минута чисто":     "A Clean Minute",
	"Три минуты чисто": "Three Clean Minutes",
	"Выживший":         "Survivor",
	"Марафонец":        "Marathoner",
	"Вечный":           "Eternal",
	"До конца":         "To the End",
	"Костолом":         "Bonebreaker",
	"Кулак севера":     "Fist of the North",
	"Фейс об стол":     "Face on the Table",
	"Ногой об голову":  "Foot to the Head",
	"Зубы мимо":        "Teeth Missed",
	"Зубы на улице":    "Teeth on the Street",
	"Мимо шамана":      "Past the Shaman",
	"Сейф не помеха":   "The Safe Is No Problem",
	"Пацифист":         "Pacifist",
	"Не оглядывайся":   "Don't Look Back",
	"Новый облик":      "New Look",
	"Примерочная":      "Fitting Room",
	"Модник":           "Fashionista",
	"Гардероб":         "Wardrobe",
	"Полный шкаф":      "Full Closet",
	"Десятка":          "The Ten",
	"Пятёрочка":        "The Five",
	"Три мастера":      "Three Masters",
	"Мастер улиц":      "Street Master",
	"Легенда улиц":     "Street Legend",
	"Кто тут хозяин":   "Who's the Boss",
	"Колдун":           "Sorcerer",
	"Заклинатель":      "Spellbinder",
	"Паутина в дело":   "Web to Work",
	"Паучья реакция":   "Spider Reflex",
	"Хозяин времени":   "Master of Time",
	"Зазывала":         "Barker",
	"Пульт нашёлся":    "Remote Found",
	"Открывашка":       "Opener",
	"Полкниги":         "Half the Book",
	"Всё видел":        "Seen It All",
	"Азартный":         "Gambler",
	"Три в ряд":        "Three in a Row",
	"Совпадение ×3":    "Match ×3",
	"Джекпот":          "Jackpot",
	"Бочка судьбы":     "Barrel of Fate",
	"Мутант":           "Mutant",
	"Ночная смена":     "Night Shift",
	"Быстрая нога":     "Fast Foot",
	"Всё и сразу":      "All at Once",
	"Во всех шести":    "In All Six",
	"Место в таблице":  "A Place in the Table",
	"Бесконечный режим": "Endless Mode",
	"Пробуй бесконечность": "Try Endless",
	"Время в бесконечном": "Time in Endless",
	"Эпизоды без урона": "Episodes Without Damage",
	"Скины куплены":    "Skins Bought",
	"Уровни скинов":    "Skin Levels",
	"Спеллы скина":     "Skin Spells",
	"Деньги за забег":  "Money per Run",
	"Деньги за всё время": "Money All Time",
	"Пицца за забег":   "Pizza per Run",
	"Пицца за всё время": "Pizza All Time",
	"Без удара подряд": "No Hits in a Row",
	"Пицца-пати":       "Pizza Party",

	# ── Достижения: условия ──────────────────────────────────────────────────
	"Запусти первый забег": "Start your first run",
	"Запусти бесконечный": "Start Endless",
	"Дёрни ручку":      "Pull the lever",
	"Сыграй в автомат": "Play the machine",
	"100 спинов":       "100 spins",
	"Возьми максимальный выигрыш": "Take the top prize",
	"Кинь пульт в телевизор 10 раз": "Throw the remote at the TV 10 times",
	"Поймай 20 девочек-зазывал": "Catch 20 barker girls",
	"Поймай 50 мэджик боксов": "Catch 50 magic boxes",
	"Открой 25 записей каталога": "Open 25 catalogue entries",
	"Открой весь каталог": "Open the whole catalogue",
	"Сыграй 10 пицца-пати": "Play 10 pizza parties",
	"Сыграй 10 жиробоссов": "Play 10 fat bosses",
	"Умри от бочки бомжа": "Die to a bum's barrel",
	"Сыграй забег между 3:00 и 5:00": "Play a run between 3:00 and 5:00",
	"Сыграй забег каждым купленным скином": "Play a run with every skin you own",
	"Купи любой скин":  "Buy any skin",
	"Купи 3 скина":     "Buy 3 skins",
	"Купи 7 скинов":    "Buy 7 skins",
	"Купи все скины":   "Buy every skin",
	"Любой скин до 5-го уровня": "Any skin to level 5",
	"Любой скин до 10-го уровня": "Any skin to level 10",
	"Три скина до 10-го уровня": "Three skins to level 10",
	"Все скины до 10-го уровня": "Every skin to level 10",
	"Примени спелл скина 100 раз": "Use your skin's spell 100 times",
	"Примени спелл скина 1 000 раз": "Use your skin's spell 1,000 times",
	"Притяни 50 предметов Спайди": "Pull in 50 items as Spidey",
	"Разбей 50 предметов кулаком викинга": "Smash 50 items with the viking's fist",
	"5 уводов реакцией за один забег": "5 dodges by reflex in one run",
	"10 остановок времени": "10 time stops",
	"10 сработавших резистов": "10 resists triggered",
	"200 сработавших резистов": "200 resists triggered",
	"10 мешков денег": "10 money bags",
	"100 мешков денег": "100 money bags",
	"50 $ за забег":   "$50 in one run",
	"200 $ за забег":  "$200 in one run",
	"5 000 $ заработано": "$5,000 earned",
	"100 пицц за забег": "100 pizza in one run",
	"300 пицц за забег": "300 pizza in one run",
	"700 пицц за забег": "700 pizza in one run",
	"1 000 пицц за всё время": "1,000 pizza all time",
	"10 000 пицц":     "10,000 pizza",
	"50 000 пицц":     "50,000 pizza",
	"250 000 пицц":    "250,000 pizza",
	"60 с подряд без урона": "60 s in a row without damage",
	"180 с подряд без урона": "180 s in a row without damage",
	"Выживи 3 минуты": "Survive 3 minutes",
	"Выживи 5 минут":  "Survive 5 minutes",
	"Выживи 10 минут": "Survive 10 minutes",
	"Выживи 15 минут": "Survive 15 minutes",
	"Достигни СЛИМ":   "Reach SLIM",
	"Достигни ЖИР":    "Reach FAT",
	"Достигни УБЕР":   "Reach UBER",
	"УБЕР в 10 забегах": "UBER in 10 runs",
	"УБЕР за первые 60 с забега": "UBER within the first 60 s of a run",
	"Дойди до босса":  "Reach the boss",
	"Дойди до СУПЕР ХАРДА": "Reach SUPER HARD",
	"Продержись 2 минуты в СУПЕР ХАРДЕ": "Hold out 2 minutes in SUPER HARD",
	"Пройди эпизод 1": "Clear episode 1",
	"Пройди эпизод 2": "Clear episode 2",
	"Пройди эпизод 3": "Clear episode 3",
	"Пройди все эпизоды игры": "Clear every episode in the game",
	"Эпизод 1 без единого урона": "Episode 1 without taking a single hit",
	"Все пять эпизодов без урона": "All five episodes without damage",
	"Пройди эпизод, ни разу не выйдя из СКИННИ": "Clear an episode never leaving SKINNY",
	"Пройди эпизод, ни разу не применив спелл скина": "Clear an episode never using your skin's spell",
	"Победи боссов 25 раз": "Beat bosses 25 times",
	"Победи Крокера, не получив урона": "Beat Croaker without taking damage",
	"Победи Фэт Фейса, не получив урона": "Beat Fat Face without taking damage",
	"Победи Ногу Ниндзя меньше чем за 40 с": "Beat the Ninja Foot in under 40 s",
	"Переживи проклятие шамана, не потеряв жизнь": "Survive the shaman's curse without losing a life",
	"Переживи сейф на резисте": "Survive the safe on a resist",
	"Попади в топ-10 недели": "Reach the weekly top 10",
	"Попади в топ-100 недели": "Reach the weekly top 100",
	"Возьми 1-е место недели": "Take 1st place of the week",
	"Попади в таблицу всех шести режимов за одну неделю": "Make the table in all six modes in one week",

	# ── Каталог: разделы ─────────────────────────────────────────────────────
	"ПРЕДМЕТЫ":         "ITEMS",
	"ВРАГИ":            "ENEMIES",
	"БОССЫ":            "BOSSES",

	# ── Каталог: имена ───────────────────────────────────────────────────────
	"БАК":              "BIN",
	"БАНАН":            "BANANA",
	"БОМБА":            "BOMB",
	"БОМЖ":             "BUM",
	"БОМЖ С БОЧКОЙ":    "BUM WITH A BARREL",
	"БУМБОКС":          "BOOMBOX",
	"БИТ БОП":          "BEAT BOP",
	"БИЛЕТ ЛУЗЕРА":     "LOSER'S TICKET",
	"БУТЫЛКА С ПИСЬМОМ": "MESSAGE IN A BOTTLE",
	"ВОР":              "THIEF",
	"ГРИБ":             "MUSHROOM",
	"ДЕВОЧКА-ЗАЗЫВАЛА": "BARKER GIRL",
	"ДОЛЛАР":           "DOLLAR",
	"ЖЕТОН":            "TOKEN",
	"ЗЕРКАЛО":          "MIRROR",
	"ЗЛАЯ СОБАКА":      "ANGRY DOG",
	"ЗМЕЯ":             "SNAKE",
	"ЗНАК":             "ROAD SIGN",
	"ЗОНТ":             "UMBRELLA",
	"КАМЕНЬ":           "ROCK",
	"КОКТЕЙЛЬ":         "COCKTAIL",
	"КОЛЕСО":           "WHEEL",
	"КОМПАС":           "COMPASS",
	"КОНУС":            "CONE",
	"КОРОБКА ПИЦЦЫ":    "PIZZA BOX",
	"КОСТЁР":           "BONFIRE",
	"КРОКЕР":           "CROAKER",
	"КРОКОДИЛ В ПОТОКЕ": "CROC IN THE STREAM",
	"МАСКА КЕЙСИ":      "CASEY MASK",
	"МАШИНА КОПОВ":     "POLICE CAR",
	"МЕШОК ДЕНЕГ":      "MONEY BAG",
	"МОЛОТОВ":          "MOLOTOV",
	"МУТАГЕН":          "MUTAGEN",
	"МЭДЖИК БОКС":      "MAGIC BOX",
	"НАРУЧНИКИ":        "HANDCUFFS",
	"НИНДЗЯ":           "NINJA",
	"НОГА НИНДЗЯ":      "NINJA FOOT",
	"ПАЧКА ПИЦЦЫ":      "PIZZA STACK",
	"ПЕРЧАТКА":         "GLOVE",
	"ПЕСОЧНЫЕ ЧАСЫ":    "HOURGLASS",
	"ПТИЦА":            "BIRD",
	"РОБОТ КЭН":        "ROBOT KEN",
	"РОК СТЕДИ":        "ROCK STEADY",
	"СЕЙФ":             "SAFE",
	"СИК БРЕЙН":        "SICK BRAIN",
	"ФЭТ ФЕЙС":         "FAT FACE",
	"ЧЁРНЫЙ ТУЗ":       "BLACK ACE",
	"ШАМАН":            "SHAMAN",
	"ШЕЗЛОНГ":          "DECK CHAIR",
	"ШЛЯПА МАГА":       "WIZARD HAT",
	"ШРЕДО":            "SHREDO",
	"ЭНЕРГЕТИК":        "ENERGY DRINK",
	"ЯД":               "POISON",

	# ── Каталог: описания ────────────────────────────────────────────────────
	"Еда и счёт разом. Каждый кусок — очко и шаг к следующему жиру.":
		"Food and score at once. Every slice is a point and a step to the next fat state.",
	"Деньги забега. На них покупаются скины — жир от них не растёт.":
		"The run's money. It buys skins — it won't make you fatter.",
	"Валюта автоматов. Тратится на спины, а не на скины.":
		"Machine currency. Spent on spins, not on skins.",
	"Просто и честно: летит по прямой, бьёт на единицу.":
		"Plain and honest: flies straight, hits for one.",
	"Крупный и медленный. Видно издалека, объехать мешает размер.":
		"Big and slow. Visible from afar — its size is what makes it hard to pass.",
	"Катится быстрее потока. Успеть отреагировать — весь вопрос.":
		"Rolls faster than the stream. Reacting in time is the whole question.",
	"Дорожный знак поперёк лейна. Читается плоско — тем и коварен.":
		"A road sign across the lane. It reads flat — that's what makes it sneaky.",
	"Дорожный конус, высотой в один, два или три ряда. Трёхрядный перекрывает пол-экрана — объезжай, сбить его нечем.":
		"A traffic cone one, two or three rows tall. The three-row one blocks half the screen — go around it, nothing can break it.",
	"Самый длинный предмет: обойти можно только сверху или снизу.":
		"The longest item: you can only pass above or below it.",
	"Парусит и оттого летит медленнее потока. Крупный: объезжают, а не проскакивают.":
		"It catches the wind and flies slower than the stream. Big: you go around it, you don't slip past.",
	"Единственная угроза по синусоиде. По прямой не объехать.":
		"The only threat that moves in a sine wave. You can't dodge it in a straight line.",
	"Ползёт зигзагом. По прямой её не объехать — надо читать фазу.":
		"Crawls in a zigzag. You can't dodge it straight — you have to read the phase.",
	"Разгоняется и идёт наперехват. Уходить надо заранее.":
		"Speeds up and cuts you off. You have to move early.",
	"Крадёт доллары. Единственный, кто отнимает не жизнь, а деньги.":
		"Steals dollars. The only one that takes money instead of a life.",
	"Тормозит, ведёт стволом и бьёт одиночным. Ствол замер — сходи с линии.":
		"It stops, tracks you with the barrel and fires a single shot. Barrel frozen — get off the line.",
	"Бьёт и ВЫЗЫВАЕТ ПОДМОГУ: роняет наручники, пока летит.":
		"Hits and CALLS FOR BACKUP: drops handcuffs as it flies.",
	"Сковывают: пока не спадут, голова еле ползёт.":
		"They bind you: until they come off, your head barely crawls.",
	"Идёт по двум лейнам и быстрее потока. Сносит всё на пути и\nразбивается у тебя перед носом — а из неё вылезают двое.":
		"Takes two lanes and moves faster than the stream. Wrecks everything in its path and\ncrashes right in front of you — and two climb out of it.",
	"Два урона — и тем же ударом ВСКРЫВАЕТСЯ: высыпает доллары, а\nиногда и мешок. Единственная сделка в игре: жир в обмен на деньги.":
		"Two damage — and the same hit CRACKS IT OPEN: it spills dollars, and\nsometimes a bag. The only trade in the game: fat for money.",
	"Ставит бочку поперёк дороги и выпускает из неё собаку.":
		"Puts a barrel across the road and lets a dog out of it.",
	"Тормозит и бьёт. Дракула его ест — остальным лучше объехать.":
		"Slows you and hits. Dracula eats it — everyone else should go around.",
	"Зовёт двух змей и пускает их кружить вокруг себя. Мимо не пройдёшь — только между.":
		"Calls two snakes and sets them circling around him. You can't pass by — only between.",
	"Врубает волну звука и сносит ею всё, что летит навстречу.":
		"Fires a wave of sound and sweeps away everything coming at you.",
	"Выстреливает вперёд на пружине. Бьёт дальше, чем кажется.":
		"Shoots forward on a spring. Reaches further than it looks.",
	"Разливает огонь по лейну. Огонь остаётся и после броска.":
		"Spills fire along the lane. The fire stays after the throw.",
	"Дрова горят тем же огнём, что остаётся после молотова.":
		"The wood burns with the same fire the molotov leaves behind.",
	"Взрывается по кругу. Опасна не сама, а радиусом.":
		"Explodes in a circle. It's not the bomb that's dangerous, it's the radius.",
	"Взрывается пачкой кусков. Большая её родня — мини-игра ПИЦЦА-ПАТИ.":
		"Bursts into a pile of slices. Its big brother is the PIZZA PARTY mini-game.",
	"Бьёт и травит: урон плюс замедление на три секунды.":
		"Hits and poisons: damage plus three seconds of slowdown.",
	"Не бьёт — разливается под ноги и вяжет на четыре секунды.":
		"No damage — it spreads under your feet and binds you for four seconds.",
	"Урона нет — есть занос. Самая частая причина влететь в следующее.":
		"No damage — just a skid. The most common reason you fly into the next thing.",
	"Урона нет — есть вязкость. Влип — не успел уйти от следующего.":
		"No damage — just drag. Stuck means you don't get away from the next one.",
	"Урона нет — есть четыре секунды заплетающихся ног.":
		"No damage — just four seconds of stumbling.",
	"Замедляют МИР, а не тебя: время на то, чтобы разобрать завал.":
		"They slow the WORLD, not you: time to read your way out of the pile.",
	"Отражает мир на пять секунд: фон наоборот, поток идёт слева.":
		"Mirrors the world for five seconds: background reversed, the stream comes from the left.",
	"Сбивает направление на пять секунд: свайп работает наоборот.":
		"Scrambles direction for five seconds: swiping works backwards.",
	"Восемь секунд: цвета наизнанку, шаг медленнее, и всё вокруг пицца.":
		"Eight seconds: colours inside out, slower steps, and everything around is pizza.",
	"Разгоняет голову. Быстрее — значит и в стену быстрее.":
		"Speeds up your head. Faster also means faster into a wall.",
	"Щит на один удар. Ломается вместе с тем, что в тебя прилетело.":
		"A shield for one hit. It breaks along with whatever hit you.",
	"Забирает спелл. Скин остаётся, а бить ему нечем.":
		"Takes your spell away. The skin stays, but it has nothing to hit with.",
	"Три секунды притягивает к голове всю добычу с экрана.":
		"For three seconds it pulls every pickup on screen to your head.",
	"Превращает всё на экране в добычу. Секунда — и стало пусто.":
		"Turns everything on screen into loot. One second and the screen is clear.",
	"Редчайшая склянка. Съел — стал ЖИРОБОССОМ и держишь жир тапами.":
		"The rarest vial. Eat it and you become the FAT BOSS, holding your fat by tapping.",
	"Светится оранжевым, как мутаген зелёным. Поймал — началась ПИЦЦА-ПАТИ.":
		"Glows orange the way the mutagen glows green. Catch it and the PIZZA PARTY begins.",
	"Ставка, а не награда: выплюнет что угодно — от пиццы до змеи.":
		"A bet, not a reward: it spits out anything from pizza to a snake.",
	"Проигрышный билет: обнуляет удачу на автоматах.":
		"A losing ticket: it zeroes your luck on the machines.",
	"Тапай его на лету: каждый тап растит мешок и число на нём, поймал — получил столько долларов. Раздутый не горит и ломает всё, во что врежется. У пирата — вдвое щедрее.":
		"Tap it in flight: every tap grows the bag and the number on it, and catching it pays you that many dollars. A swollen bag doesn't burn and smashes whatever it hits. With the pirate it pays double.",
	"Младшая родня босса. Три вида: сюрикены, рывок и дым.":
		"The boss's little cousins. Three kinds: shuriken, dash and smoke.",
	"Конец КАНАЛИЗАЦИИ. Сюрикены, рывки и дым, закрывающий экран.":
		"The end of the SEWER. Shuriken, dashes and smoke that blots out the screen.",
	"Конец УЛИЦЫ. Снайпер, картечь и пасть, которую отбивают тапами.":
		"The end of the STREET. A sniper, buckshot and jaws you beat back by tapping.",
	"Хозяин КЛУБА. Охрана, полиция, девочки — и рывок его самого.":
		"The owner of the CLUB. Guards, police, girls — and his own charge.",
	"Тот, кто в шлеме. Последний в списке — и не случайно.":
		"The one in the helmet. Last on the list, and not by accident.",
	"Жестянка с антенной. Пока не встречалась — но встретится.":
		"A tin can with an antenna. Not seen yet — but you will.",
	"Кабан в розовой бандане. Пока не встречался — но встретится.":
		"A boar in a pink bandana. Not seen yet — but you will.",
	"Носорог в каске. Пока не встречался — но встретится.":
		"A rhino in a helmet. Not seen yet — but you will.",
	"Розовый мозг на щупальцах. Пока не встречался — но встретится.":
		"A pink brain on tentacles. Not seen yet — but you will.",

	# ── Задания: названия ────────────────────────────────────────────────────
	"Первая минута":    "First Minute",
	"Прогулка":         "A Walk",
	"Долгий путь":      "The Long Way",
	"Утренний перекус": "Morning Snack",
	"Большой пирог":    "Big Pie",
	"Жирный день":      "Fat Day",
	"Карманные деньги": "Pocket Money",
	"Коллектор":        "Collector",
	"Худой":            "Skinny",
	"Стройный":         "Slim",
	"Жирный":           "Fat",
	"Убер":             "Uber",
	"Растём":           "Growing",
	"Двойной":          "Double",
	"Везунчик":         "Lucky One",
	"Автомат ждёт":     "The Machine Awaits",
	"Дёргай ручку":     "Pull the Lever",
	"Запасной":         "Spare",
	"Пируэт":           "Pirouette",
	"На скорости":      "At Speed",
	"Лети, Нормальдо!": "Fly, Normaldo!",

	# ── Задания: условия ─────────────────────────────────────────────────────
	"Выживи 60 сек в кампании": "Survive 60 s in the campaign",
	"Выживи 3 минуты в кампании": "Survive 3 minutes in the campaign",
	"Выживи 3 мин в бесконечном режиме": "Survive 3 min in Endless",
	"Выживи 5 минут в бесконечном режиме": "Survive 5 minutes in Endless",
	"Выживи 8 минут в бесконечном режиме": "Survive 8 minutes in Endless",
	"Дойди до СУПЕР ХАРДА в бесконечном": "Reach SUPER HARD in Endless",
	"Запусти бесконечный режим": "Start Endless mode",
	"Съешь 100 пицц за один забег": "Eat 100 pizza in one run",
	"Съешь 500 пицц за день": "Eat 500 pizza in a day",
	"Съешь 1000 пицц за день": "Eat 1000 pizza in a day",
	"Съешь 5000 пицц за день": "Eat 5000 pizza in a day",
	"Собери 30 $ за один забег": "Collect $30 in one run",
	"Собери 150 $ за день": "Collect $150 in a day",
	"Собери 400 $ за день": "Collect $400 in a day",
	"Достигни состояния Стройный": "Reach the Slim state",
	"Достигни состояния Жир": "Reach the Fat state",
	"Достигни Жир в кампании": "Reach Fat in the campaign",
	"Достигни Убер жир": "Reach Uber fat",
	"Достигни Убер жир в одном заезде": "Reach Uber fat in a single run",
	"Прокачай скин до 2-го уровня": "Level a skin to 2",
	"Прокачай скин до 5-го уровня": "Level a skin to 5",
	"Достигни 10-го уровня скина": "Reach skin level 10",
	"Купи любой скин в магазине": "Buy any skin in the shop",
	"Сделай 1 спин в автомате": "Make 1 spin on the machine",
	"Получи совпадение ×2 или выше": "Get a ×2 match or better",
	"Получи совпадение ×3 в автомате": "Get a ×3 match on the machine",
	"Сыграй эпизод":    "Play an episode",
	"Сыграй эпизод 5 раз": "Play an episode 5 times",
	"Пройди эпизод 1 — победи Ногу Ниндзя": "Clear episode 1 — beat the Ninja Foot",
	"Пройди эпизод 2 — победи Крокодила": "Clear episode 2 — beat the Croc",
	"Пройди эпизод 3 — победи Хозяина клуба": "Clear episode 3 — beat the Club Owner",
	"Пройди все три эпизода": "Clear all three episodes",
	"Пройди кампанию полностью": "Clear the whole campaign",
	"Пройди эпизод, не получив урона": "Clear an episode without taking damage",

	# ── Задания: главы и состояния ───────────────────────────────────────────
	"Глава 1 — Первый полёт": "Chapter 1 — First Flight",
	"Глава 2 — Канализация": "Chapter 2 — The Sewer",
	"Глава 3 — Улица":  "Chapter 3 — The Street",
	"Глава 4 — Дорога в клуб": "Chapter 4 — Road to the Club",
	"Глава 5 — Бесконечность": "Chapter 5 — Endless",
	"Глава 6 — Легенда": "Chapter 6 — Legend",
	"Завершена":        "Complete",
	"Не завершена":     "Not complete",
	"Кампания пройдена": "Campaign cleared",
	"Жир достигнут":    "Fat reached",
	"Жир не достигнут": "Fat not reached",
	"0 / 1 спин":       "0 / 1 spin",
	"1 / 1 спин":       "1 / 1 spin",
	"0 / 1 кампания":   "0 / 1 campaign",
	"1 / 1 кампания":   "1 / 1 campaign",
	"0 / 1 бесконечность": "0 / 1 endless",
	"1 / 1 бесконечность": "1 / 1 endless",
	" / Убер":          " / Uber",

	# ── Экран заданий ────────────────────────────────────────────────────────
	"ИДЁТ":             "IN PROGRESS",
	"✓ ЗАБРАНО":        "✓ CLAIMED",
	"НОВОЕ ЗАДАНИЕ ЧЕРЕЗ": "NEW QUEST IN",
	"+1 жетон":         "+1 token",

	# ── Скины: редкость и описания ───────────────────────────────────────────
	# ИМЕНА СКИНОВ НЕ ПЕРЕВОДЯТСЯ — это имена. Исключение только там, где имя
	# и есть обычное слово («ПИРАТ», «ВИКИНГ»): по-английски оно читается так же.
	"Обычный":          "Common",
	"Редкий":           "Rare",
	"Эпический":        "Epic",
	"Легендарный":      "Legendary",
	"Классик":          "Classic",
	# Имена скинов. Раньше пять из них считались именами собственными и в
	# словаре не значились — на английском так и висели кириллицей. Теперь
	# английская форма есть у каждого: «НОРМАЛЬДО» не становится переводом, но
	# латиницей писаться обязан.
	"НОРМАЛЬДО":        "NORMALDO",
	"ВИКИНГ":           "VIKING",
	"ТАЙК МАЙСОН":      "TYKE MYSON",
	"КУСС":             "KUSS",
	"НАЙТМЕН":          "NIGHTMAN",
	"ПУГАЛО":           "SCARECROW",
	"КЛОУН":            "CLOWN",
	# «МАЛЬЧИК, КОТОРЫЙ ВЫЖИЛ» уже лежит ниже, среди венцов: так зовут
	# способность этого же скина на 10-м уровне. Второй раз тот же ключ GDScript
	# не прощает — словарь с повтором не собирается вовсе, и перевод пропадает
	# весь разом.
	"ГЛАЙД":            "GLIDE",
	"ПАУК САПИЕНС":     "SPIDER SAPIENS",
	"ДРАКУЛА":          "DRACULA",
	"ВОЛШЕБНИК":        "WIZARD",
	"ГааР":             "GaaR",
	"САНТА":            "SANTA",
	"Тот самый. Ничего лишнего — только голова и голод.":
		"The one and only. Nothing extra — just a head and hunger.",
	"Бьёт первым. Разговаривает потом. Обычно не разговаривает.":
		"Hits first. Talks later. Usually doesn't talk.",
	"Приплыл за пиццей. Остался за добавкой.":
		"Sailed in for pizza. Stayed for seconds.",
	"Карту потерял. Пиццу нашёл.":
		"Lost the map. Found the pizza.",
	"Учился двадцать лет. Умеет останавливать время и жевать.":
		"Studied for twenty years. Can stop time and chew.",
	"Мальчик, который выжил. И проголодался.":
		"The boy who lived. And got hungry.",
	"Улыбку вырезали ножом. Улыбается всё равно.":
		"The smile was cut with a knife. Smiles anyway.",
	"Подарки роздал. Ужин оставил себе.":
		"Gave away the presents. Kept dinner.",
	"Пять веков на диете. Сорвался на пепперони.":
		"Five centuries on a diet. Broke it on pepperoni.",
	"Почему так серьёзно? Пицца же остывает.":
		"Why so serious? The pizza's getting cold.",
	"Этому городу нужен герой. Городу досталась голова.":
		"This city needs a hero. The city got a head.",
	"С большой силой приходит большой аппетит.":
		"With great power comes a great appetite.",
	"Лопатка в руке, кепка набок. Кухня закрыта.":
		"Spatula in hand, cap sideways. Kitchen's closed.",
	"Считает калории. Себе не верит.":
		"Counts calories. Doesn't believe himself.",

	# ── Способности скинов ───────────────────────────────────────────────────
	"ВЗРЫВНОЙ КУЛАК":   "EXPLOSIVE FIST",
	"Удар кулаком перед собой — взрыв сносит всё вплотную":
		"A punch straight ahead — the blast clears everything close",
	"УДАР ПЕРЧАТКОЙ":   "GLOVE PUNCH",
	"Короткий хук по цели перед собой": "A short hook at the target ahead",
	"ШТУРВАЛ":          "SHIP'S WHEEL",
	"Штурвал прошивает всё на линии и не разбивается":
		"The wheel punches through everything on the line and doesn't break",
	"ВЫСТРЕЛ ПАЛОЧКОЙ": "WAND SHOT",
	"Выстрел в сторону тапа: во что попал — то стало долларом":
		"A shot toward your tap: whatever it hits turns into a dollar",
	"ВСПЫШКА СВЕТА":    "FLASH OF LIGHT",
	"Вспышка обнуляет ВСЁ на экране разом. Откат самый долгий — 10 секунд":
		"The flash wipes EVERYTHING on screen at once. Longest cooldown — 10 seconds",
	"ЧЁРНЫЕ ПТИЦЫ":     "BLACK BIRDS",
	"Стая чёрных птиц срывается с головы и разлетается в разные стороны":
		"A flock of black birds bursts off your head and scatters",
	"РАСЧИСТКА":        "CLEAR-OUT",
	"Во что попал — то стало мэджик боксом. Откат 3 секунды":
		"Whatever it hits becomes a magic box. Cooldown 3 seconds",
	"НЕВИДИМОСТЬ":      "INVISIBILITY",
	"На 2 секунды исчезаешь — препятствия пролетают сквозь":
		"You vanish for 2 seconds — obstacles fly right through",
	"КОЛОДА КАРТ":      "DECK OF CARDS",
	"Четыре карты крестом: бьют плохое, отскакивают от краёв и возвращаются":
		"Four cards in a cross: they hit the bad stuff, bounce off the edges and come back",
	"БЭТ-СЮРИКЕН":      "BAT-SHURIKEN",
	"Батаранг уходит в сторону тапа, вращаясь на лету":
		"The batarang flies toward your tap, spinning as it goes",
	"Паутина ломает всё плохое на линии и утаскивает первую добычу":
		"The web breaks everything bad on the line and drags back the first pickup",
	"ЭЛЕКТРО-РЫВОК":    "ELECTRO DASH",
	"Глотнул энергетик — и рывком в точку тапа, сквозь всё подряд":
		"One gulp of energy drink and you dash to your tap, straight through everything",
	"БРОСОК ЛОПАТКИ":   "SPATULA THROW",
	"Лопатка летит в сторону тапа и сносит одну цель":
		"The spatula flies toward your tap and takes out one target",
	"РЫГАЛИТИ":         "BELCHALITY",
	"Двойной тап — могучая отрыжка летит в сторону тапа и сносит всё на пути":
		"Double tap — a mighty belch flies at your tap and clears everything in its path",
	"АЭРОДИНАМИКА":     "AERODYNAMICS",
	"Жир вообще не замедляет — на любом весе остаёшься шустрым":
		"Fat doesn't slow you at all — you stay quick at any weight",
	"ПОВЫШЕННАЯ ЛОВКОСТЬ": "HEIGHTENED AGILITY",
	"Паук слушается мгновенно — увороты даются легко на любом жире":
		"The spider responds instantly — dodging is easy at any weight",
	"СОКРОВИЩЕ":        "TREASURE",
	"Рейт на деньги ×3 — каждый доллар считается втройне":
		"Money rate ×3 — every dollar counts triple",
	"РАЗМЕН":           "EXCHANGE",
	"ОТЖОР ЛЮДЕЙ":      "FEEDING ON PEOPLE",
	"Сбил человека — и сразу толстеешь на 3 пиццы. Откат 3 секунды":
		"Knock down a person and you fatten by 3 pizza at once. Cooldown 3 seconds",

	# ── Венцы 10-го уровня ───────────────────────────────────────────────────
	"БЫСТРЫЕ КУЛАКИ":   "FAST FISTS",
	"Откат удара перчаткой короче на 1 секунду": "Glove punch cooldown is 1 second shorter",
	"ДВЕ ЛОПАТКИ":      "TWO SPATULAS",
	"Бросок уходит двумя лопатками подряд — вторая летит следом":
		"The throw sends two spatulas in a row — the second follows the first",
	"ДВОЙНАЯ ВЫГОДА":   "DOUBLE PROFIT",
	"Все доллары за забег идут ×2": "Every dollar in the run counts ×2",
	"МАЛЬЧИК, КОТОРЫЙ ВЫЖИЛ": "THE BOY WHO LIVED",
	"Один раз за забег переживаешь смертельный удар":
		"Once per run you survive a lethal hit",
	"ПАУЧЬЯ РЕАКЦИЯ":   "SPIDER REFLEX",
	"Повышенная ловкость срабатывает сама раз в 10 секунд":
		"Heightened agility fires on its own once every 10 seconds",
	"ОСТАНОВКА ВРЕМЕНИ": "TIME STOP",
	"Раз в 30 секунд время само замедляется на 3 секунды":
		"Once every 30 seconds time slows itself for 3 seconds",

	# ── Имена предметов в резистах ───────────────────────────────────────────
	"банан":            "banana",
	"бомж":             "bum",
	"бочка":            "barrel",
	"бутылка":          "bottle",
	"вор":              "thief",
	"змея":             "snake",
	"камень":           "rock",
	"коктейль":         "cocktail",
	"компас":           "compass",
	"конус":            "cone",
	"коп":              "cop",
	"наручники":        "handcuffs",
	"перчатка":         "glove",
	"пиво":             "beer",
	"птица":            "bird",
	"сейф":             "safe",
	"собака":           "dog",
	"чек лузера":       "loser's ticket",
	"чёрная карта":     "black card",
	"шаман":            "shaman",
	"штурвал":          "ship's wheel",
	"яд":               "poison",
	"урну":             "the bin",
	"змею":             "the snake",
	"перчатку":         "the glove",
	"банановую кожуру": "the banana peel",
	"огонь":            "fire",
	"доллар":           "dollar",
	"жетон":            "token",
	"предмет":          "item",
	" (скоро)":         " (soon)",

	# ── Таблица лидеров ──────────────────────────────────────────────────────
	"ЧЕТЫРЕ ТАБЛИЦЫ":   "FOUR TABLES",
	# Текст подсказки склеен в коде из трёх кусков — ключом служит СКЛЕЙКА,
	# а не куски: до перевода доходит уже целая строка.
	"Своя таблица у каждого эпизода и у Бесконечного режима. В зачёт идёт лучший забег за неделю. Эпизоды одинаковой длины у всех, поэтому счёт в них сравним честно; в Бесконечном сравнивается, кто уехал дальше.":
		"Every episode and Endless mode has its own table. Your best run of the week counts. Episodes are the same length for everyone, so scores compare fairly; in Endless it's about who got further.",
	"ЭПИЗОД 2":         "EPISODE 2",
	"ЭПИЗОД 3":         "EPISODE 3",
	"ЭПИЗОД 4":         "EPISODE 4",
	"ЭПИЗОД 5":         "EPISODE 5",
	"ТЫ":               "YOU",
	"Загрузка…":        "Loading…",
	"Спрашиваем сервер…": "Asking the server…",
	"ПОКАЗАТЬ В СПИСКЕ": "SHOW IN THE LIST",
	"ВЕСЬ МОЙ ПРОФИЛЬ": "MY FULL PROFILE",
	"Про него пока не знаем": "We don't know about them yet",
	"Сервер не назвал этого игрока": "The server didn't name this player",
	"Остальное пока не спросить": "The rest can't be asked for yet",
	"В других режимах на этой неделе не бегал": "No runs in other modes this week",
	"Сначала пройди эпизод %d": "Clear episode %d first",
	"Сначала открой Бесконечный режим": "Unlock Endless mode first",
	"Пройди все эпизоды": "Clear every episode",
	"Скинов":           "Skins",
	"Эпизодов":         "Episodes",
	"Книга":            "Book",
	"Таблица не пришла: не удалось войти на сервер.":
		"The table didn't arrive: couldn't sign in to the server.",
	"\nПопробуй позже.": "\nTry again later.",
	"\nПопробуй позже — результат последнего забега уже засчитан.":
		"\nTry again later — your last run has already been counted.",
	"\nРезультат последнего забега тоже не ушёл на сервер.":
		"\nYour last run didn't reach the server either.",
	"запрос не ушёл (%s)": "the request didn't go through (%s)",
	"нет связи с сервером (%s)": "no connection to the server (%s)",
	"сервер ответил ошибкой (%d)": "the server answered with an error (%d)",
	"сервер отказал в доступе (%d)": "the server refused access (%d)",
	"функция не развёрнута на сервере (404)": "the function isn't deployed on the server (404)",

	# ── Автомат ──────────────────────────────────────────────────────────────
	"КРУТИТЬ":          "SPIN",
	"КРУТИТЬ  1":       "SPIN  1",
	"НЕТ ЖЕТОНОВ":      "NO TOKENS",
	"Жетоны дают за задания и уровни скина": "Tokens come from quests and skin levels",
	"ПРИЗЫ":            "PRIZES",
	"ВЫИГРЫШ":          "WIN",
	"ДЖЕКПОТ":          "JACKPOT",
	"ДЖЕКПОТ!":         "JACKPOT!",
	"ТРИ В РЯД":        "THREE IN A ROW",
	"ДВА В РЯД":        "TWO IN A ROW",
	"ТРИ ОДИНАКОВЫХ — КРУПНЫЙ ПРИЗ": "THREE ALIKE — BIG PRIZE",
	"ТРИ ПИЦЦЫ":        "THREE PIZZAS",
	"ДВЕ ПИЦЦЫ":        "TWO PIZZAS",
	"ТРИ ДОЛЛАРА":      "THREE DOLLARS",
	"ДВА ДОЛЛАРА":      "TWO DOLLARS",
	"ТРИ ЖЕТОНА":       "THREE TOKENS",
	"ДВА ЖЕТОНА":       "TWO TOKENS",
	"+2 жетона":        "+2 tokens",
	"+3 жетона":        "+3 tokens",
	"+ ЖИР":            "+ FAT",
	"+ УБЕР ЖИР":       "+ UBER FAT",
	"ПОСЛЕДНИЕ СПИНЫ":  "LAST SPINS",
	"пока ни одного":   "none yet",
	"ОДИН":             "ONE",
	"ОБЫЧНЫЙ":          "COMMON",
	"РЕДКИЙ":           "RARE",
	"ЦЕННЫЙ":           "VALUABLE",
	"СМЕНИТЬ СКИН":     "CHANGE SKIN",
	"Финальная стадия и +1 жизнь": "Final stage and +1 life",
	"СВАЙПАЙ":          "SWIPE",
	"СВАЙПАЙ ВЛЕВО И ВПРАВО": "SWIPE LEFT AND RIGHT",

	# ── Уведомления ──────────────────────────────────────────────────────────
	"Пицца стынет":     "The pizza's getting cold",
	"Нормальдо смотрит на сковородку и грустит.":
		"Normaldo is staring at the pan and feeling sad.",
	"Сегодня ноль пицц": "Zero pizza today",
	"Это можно поправить за один забег.": "One run fixes that.",
	"Вернись — и я ничего не скажу": "Come back and I won't say a word",
	"На входе бонус «как давно не виделись».": "There's a \"long time no see\" bonus at the door.",
	"В канализации тихо…": "It's quiet in the sewer…",
	"Слишком тихо. Ниндзи это нравится.": "Too quiet. The ninja likes that.",
	"Свежие задания дня": "Fresh daily quests",
	"Учитель прокатил три новых задачи. Логин-бонус ждёт у двери.":
		"The teacher rolled out three new tasks. The login bonus is waiting at the door.",
	"Бесплатный спин валяется в автомате": "A free spin is sitting in the machine",
	"Прокрути и не возвращайся к работе.": "Give it a spin and don't go back to work.",
	"Твой скин просит апа": "Your skin wants a level",
	"%s, твой скин просит апа": "%s, your skin wants a level",
	"Один нормальный забег — и уровень в кармане.": "One decent run and the level is yours.",
	"До нового уровня %s оставался один забег.": "%s was one run away from a new level.",
	"%s вот-вот возьмёт уровень %d": "%s is about to hit level %d",
	"Мастерство близко": "Mastery is close",
	"Ещё чуть-чуть, и тебе капнет жетон.": "A little more and a token drops for you.",
	"Стрик %d дней висит на волоске": "Your %d-day streak is hanging by a thread",
	"Один забег — и стрик целый.": "One run and the streak is safe.",
	" Стрик %d дней — не теряй.": " A %d-day streak — don't lose it.",
	"Нога Ниндзя зевает": "The Ninja Foot is yawning",
	"Серьёзно, он уже зевает. Сделай ему больно.": "Seriously, he's yawning. Go hurt him.",
	"Крокодил не мигает": "The Croc doesn't blink",
	"Второй эпизод ждёт. Он тоже ждёт, и он голоднее.":
		"The second episode is waiting. So is he, and he's hungrier.",
	"Хозяин клуба звонит": "The Club Owner is calling",
	"Последний эпизод. Трубку он не положит.": "The last episode. He won't hang up.",
	"Бесконечный открыт": "Endless is unlocked",
	"Канализация теперь без конца. Проверь, на сколько хватит.":
		"The sewer has no end now. See how far you last.",
	"Учитель машет страницей": "The teacher is waving a page",
	"Но не до конца. Заглянешь?": "But not all the way. Coming to look?",
	"Учитель закрыл книгу": "The teacher closed the book",
	"Глава «%s» собрана — забирай награду.": "Chapter \"%s\" is complete — claim your reward.",
	"Тебе пришёл подарок": "A gift arrived for you",
	"%d незабранных награды в канализации.": "%d unclaimed rewards in the sewer.",
	"Глава":            "Chapter",
	"скин":             "skin",

	# ── Реплики боссов ───────────────────────────────────────────────────────
	"Босс уничтожит всю пиццу в городе.\nНе пытайся его остановить, Нормальдо!":
		"The boss will destroy every pizza in the city.\nDon't try to stop him, Normaldo!",
	"КРОКОДИЛ":         "THE CROC",
	"Стой смирно, черепашка.\nЯ никогда не мажу дважды.":
		"Hold still, little turtle.\nI never miss twice.",
	"ХОЗЯИН КЛУБА":     "THE CLUB OWNER",
	"Ты не в списке.\nСейчас подойдут мои люди.":
		"You're not on the list.\nMy people are on their way.",
	"КАПИТАН ПОЛИЦИИ":  "POLICE CAPTAIN",
	"Приём! Пицца уходит на юг.\nВысылайте всех.":
		"Come in! The pizza is heading south.\nSend everyone.",
	"Отбой. Я вас предупреждал.": "Stand down. I did warn you.",
	"СТАРЫЙ ПИРАТ":     "OLD PIRATE",
	"СТАРЫЙ ПИРАТ!":    "OLD PIRATE!",
	"Моя набережная, парень.": "My waterfront, kid.",
	"Моя набережная, парень.\nПокажи, что у тебя в руках.":
		"My waterfront, kid.\nShow me what's in your hands.",
	"РЫЖИЙ БОМЖ":       "RED-HAIRED BUM",
	"СЕРЫЙ БОМЖ":       "GREY BUM",
	"КОРОЛЬ!":          "KING!",
	"ПИРАТА В БОЙ!":    "PIRATE, GO!",
	"СТАРЫЙ ПИРАТ ЗАДАСТ ЕМУ ЖАРУ!": "THE OLD PIRATE WILL GIVE HIM HELL!",
	"ПОРВИ ЕГО!!":      "TEAR HIM UP!!",
	"У-У-У!!":          "WOO-OO!!",
	"ПОБЕДА":           "VICTORY",
	"БЕЙ!":             "HIT!",
	"БЛОК!":            "BLOCK!",
	"БЛОКИРУЙ!":        "BLOCK IT!",
	"УКЛОНЯЙСЯ!":       "DODGE!",
	"ДВИГАЙСЯ!":        "MOVE!",
	"ПАРИРОВАЛ!":       "PARRIED!",
	"ДВОЙНОЕ НАЖАТИЕ — УДАР": "DOUBLE TAP TO STRIKE",

	# ── Жиробосс и мини-игры ─────────────────────────────────────────────────
	"ЖИРОБОСС":         "FAT BOSS",
	"ЖИИИРРР":          "FAAAT",
	"ЖИИИРРР!!!":       "FAAAT!!!",
	"Я ЧУВСТВУЮ...":    "I CAN FEEL IT...",
	"ТАПАЙ":            "TAP",
	"ТАПАЙ!":           "TAP!",
	"ЖИР — ТАПАЙ, ЧТОБЫ ДЕРЖАТЬСЯ": "FAT — TAP TO HOLD ON",
	"ДВИГАЙ":           "MOVE",
	"свернулась":       "wrapped up",

	# ── Всплывающие надписи в забеге ─────────────────────────────────────────
	"РЕЗИСТ!":          "RESIST!",
	"НЕУЯЗВИМ!":        "INVULNERABLE!",
	"ВТОРОЙ ШАНС!":     "SECOND CHANCE!",
	"ПАУЧЬЯ РЕАКЦИЯ!":  "SPIDER REFLEX!",
	"ВРЕМЯ ЗАМЕДЛЕНО":  "TIME SLOWED",
	"МАГНИТ!":          "MAGNET!",
	"ЗЕРКАЛО!":         "MIRROR!",
	"РЕВЕРС!":          "REVERSE!",
	"ГРИБЫ!":           "SHROOMS!",
	"СКОВАН!":          "BOUND!",
	"ПРОКЛЯТИЕ!":       "CURSE!",
	"УСКОРЕНИЕ!":       "SPEED UP!",
	"ЗЗЗАП!":           "ZZZAP!",
	"ЖИР СГОРЕЛ!":      "FAT BURNED!",
	"БЕЗ ПОТЕРИ ЖИРА!": "NO FAT LOST!",
	"НЕ ЗАМЕДЛИТЬ!":    "CAN'T BE SLOWED!",
	"И ТАК НОЛЬ":       "ALREADY ZERO",
	"×2 МЕШОК!":        "×2 BAG!",
	"+1 ЖЕТОН":         "+1 TOKEN",
	"Перезарядка":      "Recharging",

	# ── Кружки способностей в забеге ─────────────────────────────────────────
	"НЕУЯЗВИМОСТЬ":     "INVULNERABILITY",
	"Маска Кейси — неуязвимость к урону.": "Casey mask — immune to damage.",
	"РЕВЕРС":           "REVERSE",
	"Компас сбил направление: свайп работает наоборот.":
		"The compass scrambled your direction: swiping works backwards.",
	"Мир отражён: поток идёт слева.": "The world is mirrored: the stream comes from the left.",
	"ГРИБЫ":            "SHROOMS",
	"Цвета наизнанку, шаг медленнее, всё вокруг пицца.":
		"Colours inside out, slower steps, everything around is pizza.",
	"Иммунитет к замедляющим предметам.": "Immune to slowing items.",
	"БАНКА КОЛЫ":       "CAN OF COLA",
	"Голова двигается быстрее.": "Your head moves faster.",
	"Раз в 10 c один удар уходит в пустоту сам.":
		"Once every 10 s one hit misses on its own.",
	"Раз в 30 c мир сам замедляется на 3 c.":
		"Once every 30 s the world slows itself for 3 s.",

	# ── Уровни ───────────────────────────────────────────────────────────────
	"КАНАЛИЗАЦИЯ":      "THE SEWER",
	"ДВОР":             "THE YARD",
	"КЛУБ":             "THE CLUB",
	"ПЛЯЖ":             "THE BEACH",
	"РЕКА":             "THE RIVER",
	"Выберись из канализации": "Get out of the sewer",
	"Найди дорогу к клубу": "Find the way to the club",
	"Направляйся к клубу": "Head for the club",
	"Найди вход в клуб": "Find the way into the club",
	"Исследуй прибрежную зону": "Explore the shoreline",

	# ── Состояния жира ───────────────────────────────────────────────────────
	"СКИННИ":           "SKINNY",
	"СЛИМ":             "SLIM",
	"УБЕР":             "UBER",

	# ── Экран достижений ─────────────────────────────────────────────────────
	"ГЛАВЫ":            "CHAPTERS",
	"В ПРОЦЕССЕ":       "IN PROGRESS",
	"БЕСКОНЕЧНЫЙ ОТКРЫТ": "ENDLESS UNLOCKED",
	"БЕСКОНЕЧНЫЙ\nРЕЖИМ": "ENDLESS\nMODE",
	"Ещё не встречал. Дойди до него в забеге — и запись откроется.":
		"Not met yet. Reach it in a run and the entry opens.",
	"Скрытое достижение": "Hidden award",
	"2-я волна":        "2nd wave",
	"резерв":           "reserve",

	# ── Строки с подстановкой ────────────────────────────────────────────────
	# Переводится ЗАГОТОВКА, до `%`: место вызова обёрнуто в `tr()` (см. loc.gd).
	# Порядок и число подстановок обязаны совпадать с русскими — иначе строка
	# соберётся с мусором или уронит подстановку вовсе.
	"ЭПИЗОД %d":        "EPISODE %d",
	"УРОВЕНЬ %d":       "LEVEL %d",
	"УРОВЕНЬ %d!":      "LEVEL %d!",
	"УР. %d":           "LV. %d",
	"УР.%d":            "LV.%d",
	"ур. %d":           "lv. %d",
	"ур.%d":            "lv.%d",
	"ур.2":             "lv.2",
	"УРОВЕНЬ %d · %s":  "LEVEL %d · %s",
	"УРОВЕНЬ %d — НАГРАДЫ:": "LEVEL %d — REWARDS:",
	"СУПЕР ХАРД %d":    "SUPER HARD %d",
	"ВРЕМЯ  %d:%02d":   "TIME  %d:%02d",
	"#%d МЕСТО":        "#%d PLACE",
	"%s — #%d МЕСТО":   "%s — #%d PLACE",
	"НОВЫЙ РЕКОРД!  БЫЛО %d": "NEW RECORD!  WAS %d",
	"ДО РЕКОРДА НЕ ХВАТИЛО %d": "%d SHORT OF THE RECORD",
	"ЖИР «%s»":         "FAT \"%s\"",
	"+ ЖИР «%s»  (+1 ЖИЗНЬ)": "+ FAT \"%s\"  (+1 LIFE)",
	"ЖИР · %s":         "FAT · %s",
	"ЗАДАНИЕ: %s":      "QUEST: %s",
	"РЕЗИСТ: %s":       "RESIST: %s",
	"+ РЕЗИСТ: %s":     "+ RESIST: %s",
	"РЕЗИСТ · %d УРОВЕНЬ": "RESIST · LEVEL %d",
	"Откроется на %d уровне": "Unlocks at level %d",
	"Открывает %d-е состояние": "Unlocks the %d-th state",
	"Открыто %d-е состояние жира": "Fat state %d unlocked",
	"Иммунитет: %s%s":  "Immune: %s%s",
	"%d жетон":         "%d token",
	"+%d жетон":        "+%d token",
	"+%d жетона":       "+%d tokens",
	"+%d ОПЫТ":         "+%d XP",
	"+%d ж":            "+%d t",
	"+%d $ +%d ж":      "+%d $ +%d t",
	"+ %d  ×2 ДВОЙНАЯ ВЫГОДА": "+ %d  ×2 DOUBLE PROFIT",
	"МАСТЕРСТВО: %d / %d XP": "MASTERY: %d / %d XP",
	"%d / %d XP до ур. %d": "%d / %d XP to lv. %d",
	"ещё %d XP до жетона": "%d XP to a token",
	"ещё %d XP до ур. %d": "%d XP to lv. %d",
	"ещё %d пицц до жетона": "%d pizza to a token",
	"ещё %d пицц до ур.%d": "%d pizza to lv.%d",
	"Забегов: %d   ·   Рекорд: %d пицц": "Runs: %d   ·   Record: %d pizza",
	"Забегов этим скином: %d · Рекорд: %d": "Runs with this skin: %d · Record: %d",
	"Рекорд скина: %d пицц": "Skin record: %d pizza",
	"%d пицц":          "%d pizza",
	"%s · %.0f с":      "%s · %.0f s",
	"%d%% уклон":       "%d%% dodge",
	"%d%% трансф.":     "%d%% transf.",
	"%d%%→пицца":       "%d%%→pizza",
	"%d%% шанс пройти сквозь %s\nбез эффекта": "%d%% chance to pass through %s\nwith no effect",
	"%d%% шанс превратить %s в пиццу": "%d%% chance to turn %s into pizza",
	"%d%% шанс превратить %s в случайный предмет": "%d%% chance to turn %s into a random item",
	"%d%% шанс изменить %s при подборе": "%d%% chance to change %s on pickup",
	"%d%% шанс: доллар → ×3 долларов": "%d%% chance: dollar → ×3 dollars",
	"Удар засчитывается, но даёт +%d XP": "The hit still counts, but gives +%d XP",
	"Удар засчитывается, но даёт +%d $": "The hit still counts, but gives +%d $",
	"Удар засчитывается, но даёт случайный бонус": "The hit still counts, but gives a random bonus",
	"%s разбивается без вреда": "%s breaks with no harm",
	"%s — разбиваешь без вреда": "%s — you break it with no harm",
	"● Резисты: %s":    "● Resists: %s",
	"Новые жиры открываются по мере прокачки скина. Этот жир станет доступен на ":
		"New fat states open as the skin levels up. This one becomes available at level ",
	"-м уровне.":       ".",
	"Разбиваешь «":     "You break \"",
	"» без вреда для себя.": "\" with no harm to yourself.",
	"Ломает «":         "Breaks \"",
	"» без урона. Откат ": "\" with no damage. Cooldown ",
	"РЕЗИСТ · ":        "RESIST · ",
	"АКТИВКА · ":       "ACTIVE · ",
	"  —  МЕХАНИКА":    "  —  MECHANICS",

	# ── Задания и лидеры: подстановки ────────────────────────────────────────
	"%d / %d пицц":     "%d / %d pizza",
	"%d / %d $ (забег)": "%d / %d $ (run)",
	"%d / %d забегов":  "%d / %d runs",
	"%d / %d совп.":    "%d / %d matches",
	"%d / 2 кампании":  "%d / 2 campaigns",
	"%d / 3 фазы":      "%d / 3 phases",
	"%d / 3 фазы без урона": "%d / 3 phases without damage",
	"БОНУС ЗА ВХОД   +%d $": "LOGIN BONUS   +%d $",
	"ДО СБРОСА  %02d:%02d:%02d": "RESETS IN  %02d:%02d:%02d",
	"%d место · %s":    "place %d · %s",
	"%d место из %d   ·   %s": "place %d of %d   ·   %s",
	"Место появится, когда придёт таблица   ·   %s":
		"Your place shows up once the table arrives   ·   %s",
	"ПРИЗЫ ЧЕРЕЗ %s":   "PRIZES IN %s",
	"Призы через %s":   "Prizes in %s",
	"Таблица не пришла: %s.": "The table didn't arrive: %s.",
	"новое через %s":   "new one in %s",
	"%dд %dч":          "%dd %dh",
	"%dч %dм":          "%dh %dm",
	"%dм":              "%dm",
	"ВСТРЕЧЕНО  %d / %d": "MET  %d / %d",
	"ПРОЙДЕНО %d / %d": "CLEARED %d / %d",
	"%d из %d  ·  %d из %d очков": "%d of %d  ·  %d of %d points",
	"С %02d:00 до %02d:00 пуши не приходят.":
		"No push notifications between %02d:00 and %02d:00.",
	"ТАПАЙ!  %d":       "TAP!  %d",
	"Ф%d/%d":           "P%d/%d",

	# ── Остатки ──────────────────────────────────────────────────────────────
	"КОП":              "COP",
	"ПОЛУЧЕН":          "RECEIVED",
	"×0.5 длит.":       "×0.5 dur.",
	"ежедневный бонус / новые задания": "daily bonus / new quests",
	"ВОССТАНОВЛЕНИЕ АККАУНТА": "ACCOUNT RECOVERY",
	"Введи код восстановления — это связка из 4 групп hex-символов, которую игра выдала тебе на первом запуске и хранит в настройках. Если код подходит, твой прогресс (доллары, скины, рекорды, призы) подгрузится с сервера. ВАЖНО: текущий прогресс этого устройства будет заменён данными аккаунта по коду.":
		"Enter your recovery code — four groups of hex characters the game gave you on first launch and keeps in the settings. If the code matches, your progress (dollars, skins, records, prizes) is pulled from the server. IMPORTANT: this device's current progress will be replaced by the account behind the code.",

	# ── ОДНОБУКВЕННЫЕ ЗНАЧКИ ТИПОВ СПОСОБНОСТЕЙ ──────────────────────────────
	# Буква на маленьком кружке: тип способности и первая буква её названия.
	# Кириллическая «У» на английской сборке читается как сломанный шрифт, так
	# что переводить их надо — хотя ключ в одну букву и опасен сам по себе:
	# он подхватит ЛЮБУЮ надпись ровно из этой буквы, которую заведут потом.
	# Сейчас таких больше нет, и за этим следит проверка ключей по исходникам.
	"У":                "D",
	"А":                "A",
	"К":                "C",
	"Т":                "T",
	"О":                "F",
	"С":                "T",
	"Л":                "A",

	# ── Склеенные строки, ставшие заготовками ────────────────────────────────
	"Откат %d с":       "Cooldown %d s",
	"Разбиваешь «%s» без вреда для себя.": "You break \"%s\" with no harm to yourself.",
	"Ломает «%s» без урона. Откат %d с.": "Breaks \"%s\" with no damage. Cooldown %d s.",
	"Новые жиры открываются по мере прокачки скина. Этот жир станет доступен на %d-м уровне.":
		"New fat states open as the skin levels up. This one becomes available at level %d.",
}
